# Generated by Django 3.2.6 on 2021-08-24 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('key1', models.CharField(max_length=15)),
                ('key2', models.CharField(blank=True, max_length=15)),
                ('key3', models.CharField(blank=True, max_length=15)),
                ('site1', models.BooleanField(default=True)),
                ('site2', models.BooleanField(default=True)),
                ('site3', models.BooleanField(default=True)),
                ('site4', models.BooleanField(default=True)),
                ('site5', models.BooleanField(default=True)),
            ],
        ),
    ]
