# Generated by Django 3.2.6 on 2021-08-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='key1',
            field=models.CharField(default='未登録', max_length=15),
        ),
        migrations.AlterField(
            model_name='setting',
            name='key2',
            field=models.CharField(blank=True, default='未登録', max_length=15),
        ),
        migrations.AlterField(
            model_name='setting',
            name='key3',
            field=models.CharField(blank=True, default='未登録', max_length=15),
        ),
    ]
